In [1]:
'''Generar arreglo de 2 dimensiones

'''

'Generar arreglo de 2 dimensiones\n\n'

In [2]:
import numpy as np
resistencias = np.array([1E3,10E3,100E3])
resistencias

array([  1000.,  10000., 100000.])

In [3]:
resistencias.shape

(3,)

In [4]:
voltajes= np.arange(start=0, stop=100,step=10)
voltajes

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
voltajes.shape

(10,)

In [6]:
#Reacomode su forma, misma cantidad de filas pero una columna (10,1), antes estaba en 10
voltajes = voltajes.reshape(voltajes.shape[0],1)
voltajes

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80],
       [90]])

In [7]:
medidas =voltajes/resistencias
medidas

array([[0.    , 0.    , 0.    ],
       [0.01  , 0.001 , 0.0001],
       [0.02  , 0.002 , 0.0002],
       [0.03  , 0.003 , 0.0003],
       [0.04  , 0.004 , 0.0004],
       [0.05  , 0.005 , 0.0005],
       [0.06  , 0.006 , 0.0006],
       [0.07  , 0.007 , 0.0007],
       [0.08  , 0.008 , 0.0008],
       [0.09  , 0.009 , 0.0009]])

In [8]:
employee = np.array(['p','j','t'])

In [9]:
medidas[ :,(employee == 'p')]

array([[0.  ],
       [0.01],
       [0.02],
       [0.03],
       [0.04],
       [0.05],
       [0.06],
       [0.07],
       [0.08],
       [0.09]])