In [1]:
import numpy as np
'''Arreglo tiene los mismos datos, si los necesita mixtos se debe usar otra estructura'''
data2 = [[1,2,3],[4,5,6]]
arr2= np.array(data2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
arr2.ndim

2

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
np.empty((2,3,2))
#reserva espacio en memoria pero no son ceros

array([[[6.91271937e-310, 6.91271937e-310],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [6]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
np.array([1.1,2,3]).dtype
#Se convierte automaticamente al tipo que se encuentre

dtype('float64')

In [8]:
np.array([1.1,2,3], dtype=np.int32)
#estamos forzando al array ser de un tipo en específico

array([1, 2, 3], dtype=int32)

In [9]:
#conversiones
np.array(['a','b','c'])


array(['a', 'b', 'c'], dtype='<U1')

In [10]:
np.array(['a','b','c']).astype(np.float64)

ValueError: could not convert string to float: 'a'

In [11]:
np.array([1,2,3]).astype(np.float64)

array([1., 2., 3.])

In [12]:
#números numpy, string pandas porque se pueden truncar

In [13]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr


array([[1., 2., 3.],
       [4., 5., 6.]])

In [14]:
arr * arr
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [15]:

arr - arr
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [16]:
arr = np.arange(10)
arr
arr[5]
arr[5:8]
arr[5:8] = 12
arr
arr_slice = arr[5:8]
arr_slice
arr_slice[1] = 12345
arr
 #es una referencia, lo que quiere decir que cualquier cambio se actualiza el array origintal, en el caso de ocupar no alterar los datos originales se hace una copia

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [17]:
a = arr.copy()
a[1]=365
a

array([    0,   365,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [18]:
arr


array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [19]:
id(a)

139914934022016

In [20]:
id(a.copy())
#tenemos dos datos diferentes

139914934233248

In [21]:
arr_slice[:] = 64
arr
#cambia el extracto [:]

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])